spring:
  # admin
  boot:
    admin:
      client:
        username: root
        password: 123456
        instance:
          name: admin

  # RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest   

# 暴露点
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


# Eureka 公共配置
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@117.51.140.37:7500/eureka/,http://root:123456@47.93.54.81:7501/eureka/